// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"payget/app/model/internal"
)

// GenTable is the golang structure for table gen_table.
type GenTable internal.GenTable

// Fill with you ideas below.
