// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"payget/app/model/internal"
)

// GenTableColumn is the golang structure for table gen_table_column.
type GenTableColumn internal.GenTableColumn

// Fill with you ideas below.
