// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"payget/app/model/internal"
)

// SysAdSort is the golang structure for table sys_ad_sort.
type SysAdSort internal.SysAdSort

// Fill with you ideas below.
