// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"glow-admin/app/model/internal"
)

// SysOperLog is the golang structure for table sys_oper_log.
type SysOperLog internal.SysOperLog

// Fill with you ideas below.
