// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"payget/app/model/internal"
)

// SysNotice is the golang structure for table sys_notice.
type SysNotice internal.SysNotice

// Fill with you ideas below.
