// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"payget/app/model/internal"
)

// SysItemCate is the golang structure for table sys_item_cate.
type SysItemCate internal.SysItemCate

// Fill with you ideas below.
