// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"payget/app/model/internal"
)

// SysDept is the golang structure for table sys_dept.
type SysDept internal.SysDept

// Fill with you ideas below.

type DeptDTO struct {
	ID         uint
	Name       string
	Pid        int
	Note       string
	UpdateUser int
	UpdateName string
}
