// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"payget/app/model/internal"
)

// SysRoleMenu is the golang structure for table sys_role_menu.
type SysRoleMenu internal.SysRoleMenu

// Fill with you ideas below.
