// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"payget/app/model/internal"
)

// SysExample is the golang structure for table sys_example.
type SysExample internal.SysExample

// Fill with you ideas below.
