// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"payget/app/model/internal"
)

// SysRole is the golang structure for table sys_role.
type SysRole internal.SysRole

// Fill with you ideas below.
