// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"payget/app/model/internal"
)

// SysAd is the golang structure for table sys_ad.
type SysAd internal.SysAd

// Fill with you ideas below.
