// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"glow-admin/app/model/internal"
)

// SysConfig is the golang structure for table sys_config.
type SysConfig internal.SysConfig

// Fill with you ideas below.
