// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"payget/app/model/internal"
)

// SysDictData is the golang structure for table sys_dict_data.
type SysDictData internal.SysDictData

// Fill with you ideas below.
