// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"github.com/gogf/gf/os/gtime"
	"payget/app/model/internal"
)

// SysMenu is the golang structure for table sys_menu.
type SysMenu internal.SysMenu

// Fill with you ideas below.
type DTOMenu struct {
	Id         uint        `orm:"id,primary"  json:"id"`         // 主键ID
	Pid        uint        `orm:"pid"         json:"pid"`        // 父级ID
	Title      string      `orm:"title"       json:"title"`      // 菜单标题
	Icon       string      `orm:"icon"        json:"icon"`       // 图标
	Path       string      `orm:"path"        json:"path"`       // 菜单路径
	Component  string      `orm:"component"   json:"component"`  // 菜单组件
	Target     string      `orm:"target"      json:"target"`     // 目标
	Permission string      `orm:"permission"  json:"permission"` // 权限标识
	Type       uint        `orm:"type"        json:"type"`       // 类型：1目录 2菜单 3节点
	Status     uint        `orm:"status"      json:"status"`     // 是否显示：1显示 2不显示
	Note       string      `orm:"note"        json:"note"`       // 备注
	Sort       uint        `orm:"sort"        json:"sort"`       // 显示顺序
	CreateUser uint        `orm:"create_user" json:"createUser"` // 添加人
	CreateTime *gtime.Time `orm:"create_time" json:"createTime"` // 创建时间
	UpdateUser uint        `orm:"update_user" json:"updateUser"` // 更新人
	UpdateTime *gtime.Time `orm:"update_time" json:"updateTime"` // 更新时间
	Mark       uint        `orm:"mark"        json:"mark"`       // 有效标识
	Children   []*DTOMenu  `orm:"-" json:"children"`
}
