// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"glow-admin/app/model/internal"
)

// SysConfigData is the golang structure for table sys_config_data.
type SysConfigData internal.SysConfigData

// Fill with you ideas below.
