// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"payget/app/model/internal"
)

// SysLayout is the golang structure for table sys_layout.
type SysLayout internal.SysLayout

// Fill with you ideas below.
