// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"glow-admin/app/model/internal"
)

// SysLoginLog is the golang structure for table sys_login_log.
type SysLoginLog internal.SysLoginLog

// Fill with you ideas below.
