// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"payget/app/model/internal"
)

// SysMenu is the golang structure for table sys_menu.
type SysMenu internal.SysMenu

// Fill with you ideas below.
type DTOMenu struct {
	SysMenu
	Children []*DTOMenu `orm:"-" json:"children"`
}
