// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"payget/app/model/internal"
)

// SysLayoutDesc is the golang structure for table sys_layout_desc.
type SysLayoutDesc internal.SysLayoutDesc

// Fill with you ideas below.
