// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"payget/app/model/internal"
)

// SysCity is the golang structure for table sys_city.
type SysCity internal.SysCity

// Fill with you ideas below.
