// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"payget/app/model/internal"
)

// SysItem is the golang structure for table sys_item.
type SysItem internal.SysItem

// Fill with you ideas below.
