// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"payget/app/model/internal"
)

// SysLink is the golang structure for table sys_link.
type SysLink internal.SysLink

// Fill with you ideas below.
