// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"payget/app/model/internal"
)

// SysPosition is the golang structure for table sys_position.
type SysPosition internal.SysPosition

// Fill with you ideas below.
