// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"payget/app/model/internal"
)

// UmsMember is the golang structure for table ums_member.
type UmsMember internal.UmsMember

// Fill with you ideas below.
