// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"payget/app/model/internal"
)

// UmsMemberLevel is the golang structure for table ums_member_level.
type UmsMemberLevel internal.UmsMemberLevel

// Fill with you ideas below.
