// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// GenTableColumn is the golang structure for table gen_table_column.
type GenTableColumn struct {
	Id            int64       `orm:"id,primary"     json:"id"`            // 主键ID
	TableId       uint        `orm:"table_id"       json:"tableId"`       // 归属表编号
	ColumnName    string      `orm:"column_name"    json:"columnName"`    // 列名称
	ColumnComment string      `orm:"column_comment" json:"columnComment"` // 列描述
	ColumnType    string      `orm:"column_type"    json:"columnType"`    // 列类型
	JavaType      string      `orm:"java_type"      json:"javaType"`      // JAVA类型
	JavaField     string      `orm:"java_field"     json:"javaField"`     // JAVA字段名
	IsPk          int         `orm:"is_pk"          json:"isPk"`          // 是否主键（1是）
	IsIncrement   string      `orm:"is_increment"   json:"isIncrement"`   // 是否自增（1是）
	IsRequired    string      `orm:"is_required"    json:"isRequired"`    // 是否必填（1是）
	IsInsert      string      `orm:"is_insert"      json:"isInsert"`      // 是否为插入字段（1是）
	IsEdit        string      `orm:"is_edit"        json:"isEdit"`        // 是否编辑字段（1是）
	IsList        string      `orm:"is_list"        json:"isList"`        // 是否列表字段（1是）
	IsQuery       string      `orm:"is_query"       json:"isQuery"`       // 是否查询字段（1是）
	QueryType     string      `orm:"query_type"     json:"queryType"`     // 查询方式（等于、不等于、大于、小于、范围）
	HtmlType      string      `orm:"html_type"      json:"htmlType"`      // 显示类型（文本框、文本域、下拉框、复选框、单选框、日期控件）
	DictType      string      `orm:"dict_type"      json:"dictType"`      // 字典类型
	Sort          int         `orm:"sort"           json:"sort"`          // 排序
	CreateUser    uint        `orm:"create_user"    json:"createUser"`    // 添加人
	CreateTime    *gtime.Time `orm:"create_time"    json:"createTime"`    // 创建时间
	UpdateUser    uint        `orm:"update_user"    json:"updateUser"`    // 更新人
	UpdateTime    *gtime.Time `orm:"update_time"    json:"updateTime"`    // 更新时间
	Mark          uint        `orm:"mark"           json:"mark"`          // 有效标识
}
