// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// SysDept is the golang structure for table sys_dept.
type SysDept struct {
	Id         uint        `orm:"id,primary"  json:"id"`         // 主键ID
	Name       string      `orm:"name"        json:"name"`       // 部门名称
	Pid        uint        `orm:"pid"         json:"pid"`        // 上级ID
	Sort       uint        `orm:"sort"        json:"sort"`       // 排序
	Note       string      `orm:"note"        json:"note"`       // 备注说明
	CreateUser uint        `orm:"create_user" json:"createUser"` // 添加人
	CreateTime *gtime.Time `orm:"create_time" json:"createTime"` // 添加时间
	UpdateUser uint        `orm:"update_user" json:"updateUser"` // 更新人
	UpdateTime *gtime.Time `orm:"update_time" json:"updateTime"` // 更新时间
	Mark       uint        `orm:"mark"        json:"mark"`       // 有效标识
}
