// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// SysLoginLog is the golang structure for table sys_login_log.
type SysLoginLog struct {
	Id            uint        `orm:"id,primary"     json:"id"`            // 唯一性标识
	Title         string      `orm:"title"          json:"title"`         // 日志标题
	Username      string      `orm:"username"       json:"username"`      // 登录账号
	LoginIp       string      `orm:"login_ip"       json:"loginIp"`       // 登录IP地址
	LoginLocation string      `orm:"login_location" json:"loginLocation"` // 登录地区
	Browser       string      `orm:"browser"        json:"browser"`       // 浏览器类型
	Os            string      `orm:"os"             json:"os"`            // 操作系统
	Status        uint        `orm:"status"         json:"status"`        // 登录状态：0成功 1失败
	Type          uint        `orm:"type"           json:"type"`          // 操作类型：1登录系统 2注销系统 3刷新Token
	Note          string      `orm:"note"           json:"note"`          // 登录备注
	CreateUser    uint        `orm:"create_user"    json:"createUser"`    // 添加人
	CreateTime    *gtime.Time `orm:"create_time"    json:"createTime"`    // 登录时间
	UpdateUser    uint        `orm:"update_user"    json:"updateUser"`    // 更新人
	UpdateTime    *gtime.Time `orm:"update_time"    json:"updateTime"`    // 更新时间
	Mark          uint        `orm:"mark"           json:"mark"`          // 有效标记
}
