// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

// SysRoleMenu is the golang structure for table sys_role_menu.
type SysRoleMenu struct {
	RoleId uint `orm:"role_id" json:"roleId"` // 角色ID
	MenuId uint `orm:"menu_id" json:"menuId"` // 菜单ID
}
