// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// SysUser is the golang structure for table sys_user.
type SysUser struct {
	Id        uint        `orm:"id,primary" json:"id"`         // 主键ID
	Nickname  string      `orm:"nickname"   json:"nickname"`   // 昵称
	Username  string      `orm:"username"   json:"username"`   // 登录用户名
	Password  string      `orm:"password"   json:"password"`   // 登录密码
	Salt      string      `orm:"salt"       json:"salt"`       // 盐加密
	Avatar    string      `orm:"avatar"     json:"avatar"`     // 头像
	Mobile    string      `orm:"mobile"     json:"mobile"`     // 手机号码
	Email     string      `orm:"email"      json:"email"`      // 邮箱地址
	Intro     string      `orm:"intro"      json:"intro"`      // 个人简介
	Status    uint        `orm:"status"     json:"status"`     // 状态：1正常 2禁用
	Note      string      `orm:"note"       json:"note"`       // 备注
	LoginNum  uint        `orm:"login_num"  json:"login_num"`  // 登录次数
	LoginIp   string      `orm:"login_ip"   json:"login_ip"`   // 最近登录IP
	LoginTime *gtime.Time `orm:"login_time" json:"login_time"` // 最近登录时间
	CreatedBy uint        `orm:"created_by" json:"created_by"` // 添加人
	CreatedAt *gtime.Time `orm:"created_at" json:"created_at"` // 添加时间
	UpdatedBy uint        `orm:"updated_by" json:"updated_by"` // 更新人
	UpdatedAt *gtime.Time `orm:"updated_at" json:"updated_at"` // 更新时间
}
