// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// SysAd is the golang structure for table sys_ad.
type SysAd struct {
	Id          uint        `orm:"id,primary"  json:"id"`          // 主键ID
	Title       string      `orm:"title"       json:"title"`       // 广告标题
	AdSortId    uint        `orm:"ad_sort_id"  json:"adSortId"`    // 广告位ID
	Cover       string      `orm:"cover"       json:"cover"`       // 广告图片
	Type        uint        `orm:"type"        json:"type"`        // 广告格式：1图片 2文字 3视频 4推荐
	Description string      `orm:"description" json:"description"` // 广告描述
	Content     string      `orm:"content"     json:"content"`     // 广告内容
	Url         string      `orm:"url"         json:"url"`         // 广告链接
	Width       uint        `orm:"width"       json:"width"`       // 广告宽度
	Height      uint        `orm:"height"      json:"height"`      // 广告高度
	StartTime   *gtime.Time `orm:"start_time"  json:"startTime"`   // 开始时间
	EndTime     *gtime.Time `orm:"end_time"    json:"endTime"`     // 结束时间
	ViewNum     uint        `orm:"view_num"    json:"viewNum"`     // 广告点击次数
	Status      uint        `orm:"status"      json:"status"`      // 状态：1在用 2停用
	Sort        uint        `orm:"sort"        json:"sort"`        // 排序
	CreateUser  uint        `orm:"create_user" json:"createUser"`  // 添加人
	CreateTime  *gtime.Time `orm:"create_time" json:"createTime"`  // 添加时间
	UpdateUser  uint        `orm:"update_user" json:"updateUser"`  // 更新人
	UpdateTime  *gtime.Time `orm:"update_time" json:"updateTime"`  // 更新时间
	Mark        uint        `orm:"mark"        json:"mark"`        // 有效标识(1正常 0删除)
}
