// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// SysExample is the golang structure for table sys_example.
type SysExample struct {
	Id         uint        `orm:"id,primary"  json:"id"`         // 唯一性标识
	Name       string      `orm:"name"        json:"name"`       // 案例名称
	Avatar     string      `orm:"avatar"      json:"avatar"`     // 头像
	Status     uint        `orm:"status"      json:"status"`     // 状态：1正常 2停用
	Type       uint        `orm:"type"        json:"type"`       // 类型：1京东 2淘宝 3拼多多 4唯品会
	Sort       uint        `orm:"sort"        json:"sort"`       // 显示顺序
	Birthday   *gtime.Time `orm:"birthday"    json:"birthday"`   // 出生时间
	CreateUser uint        `orm:"create_user" json:"createUser"` // 添加人
	CreateTime *gtime.Time `orm:"create_time" json:"createTime"` // 添加时间
	UpdateUser uint        `orm:"update_user" json:"updateUser"` // 更新人
	UpdateTime *gtime.Time `orm:"update_time" json:"updateTime"` // 更新时间
	Mark       uint        `orm:"mark"        json:"mark"`       // 有效标记
}
