// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// SysLayout is the golang structure for table sys_layout.
type SysLayout struct {
	Id         uint        `orm:"id,primary"  json:"id"`         // 主键ID
	LocDesc    string      `orm:"loc_desc"    json:"locDesc"`    // 页面位置描述
	LocId      uint        `orm:"loc_id"      json:"locId"`      // 页面的位置
	ItemId     uint        `orm:"item_id"     json:"itemId"`     // 页面编号
	Type       uint        `orm:"type"        json:"type"`       // 类型：1系统文章 2通知公告
	TypeId     uint        `orm:"type_id"     json:"typeId"`     // 对应的类型编号
	Image      string      `orm:"image"       json:"image"`      // 图片路径
	Sort       uint        `orm:"sort"        json:"sort"`       // 显示顺序
	CreateUser uint        `orm:"create_user" json:"createUser"` // 添加人
	CreateTime *gtime.Time `orm:"create_time" json:"createTime"` // 添加时间
	UpdateUser uint        `orm:"update_user" json:"updateUser"` // 更新人
	UpdateTime *gtime.Time `orm:"update_time" json:"updateTime"` // 更新时间
	Mark       uint        `orm:"mark"        json:"mark"`       // 有效标识(1正常 0删除)
}
