// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// SysConfigData is the golang structure for table sys_config_data.
type SysConfigData struct {
	Id        uint        `orm:"id,primary" json:"id"`         // 主键ID
	Title     string      `orm:"title"      json:"title"`      // 配置标题
	Code      string      `orm:"code"       json:"code"`       // 配置编码
	Value     string      `orm:"value"      json:"value"`      // 配置值
	Options   string      `orm:"options"    json:"options"`    // 配置项
	ConfigId  uint        `orm:"config_id"  json:"config_id"`  // 配置分组ID
	Type      string      `orm:"type"       json:"type"`       // 配置类型
	Status    uint        `orm:"status"     json:"status"`     // 状态：1正常 2停用
	Sort      uint        `orm:"sort"       json:"sort"`       // 排序
	Note      string      `orm:"note"       json:"note"`       // 配置说明
	CreatedBy uint        `orm:"created_by" json:"created_by"` // 添加人
	CreatedAt *gtime.Time `orm:"created_at" json:"created_at"` // 添加时间
	UpdatedBy uint        `orm:"updated_by" json:"updated_by"` // 更新人
	UpdatedAt *gtime.Time `orm:"updated_at" json:"updated_at"` // 更新时间
}
