// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// SysLink is the golang structure for table sys_link.
type SysLink struct {
	Id         uint        `orm:"id,primary"  json:"id"`         // 唯一性标识
	Name       string      `orm:"name"        json:"name"`       // 友链名称
	Type       uint        `orm:"type"        json:"type"`       // 类型：1友情链接 2合作伙伴
	Url        string      `orm:"url"         json:"url"`        // 友链地址
	ItemId     uint        `orm:"item_id"     json:"itemId"`     // 站点ID
	CateId     uint        `orm:"cate_id"     json:"cateId"`     // 栏目ID
	Platform   uint        `orm:"platform"    json:"platform"`   // 平台：1PC站 2WAP站 3微信小程序 4APP应用
	Form       uint        `orm:"form"        json:"form"`       // 友链形式：1文字链接 2图片链接
	Image      string      `orm:"image"       json:"image"`      // 友链图片
	Status     uint        `orm:"status"      json:"status"`     // 状态：1在用 2停用
	Sort       uint        `orm:"sort"        json:"sort"`       // 显示顺序
	CreateUser uint        `orm:"create_user" json:"createUser"` // 添加人
	CreateTime *gtime.Time `orm:"create_time" json:"createTime"` // 添加时间
	UpdateUser uint        `orm:"update_user" json:"updateUser"` // 更新人
	UpdateTime *gtime.Time `orm:"update_time" json:"updateTime"` // 更新时间
	Mark       uint        `orm:"mark"        json:"mark"`       // 有效标识(1正常 0删除)
}
