// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

// SysUserRole is the golang structure for table sys_user_role.
type SysUserRole struct {
	UserId uint `orm:"user_id" json:"userId"` // 人员ID
	RoleId uint `orm:"role_id" json:"roleId"` // 角色ID
}
