// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"payget/app/dao/internal"
)

// genTableDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type genTableDao struct {
	*internal.GenTableDao
}

var (
	// GenTable is globally public accessible object for table gen_table operations.
	GenTable genTableDao
)

func init() {
	GenTable = genTableDao{
		internal.NewGenTableDao(),
	}
}

// Fill with you ideas below.
