// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"payget/app/dao/internal"
)

// genTableColumnDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type genTableColumnDao struct {
	*internal.GenTableColumnDao
}

var (
	// GenTableColumn is globally public accessible object for table gen_table_column operations.
	GenTableColumn genTableColumnDao
)

func init() {
	GenTableColumn = genTableColumnDao{
		internal.NewGenTableColumnDao(),
	}
}

// Fill with you ideas below.
