// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"payget/app/dao/internal"
)

// sysCityDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type sysCityDao struct {
	*internal.SysCityDao
}

var (
	// SysCity is globally public accessible object for table sys_city operations.
	SysCity sysCityDao
)

func init() {
	SysCity = sysCityDao{
		internal.NewSysCityDao(),
	}
}

// Fill with you ideas below.
