// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"glow-admin/app/dao/internal"
)

// sysUserDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type sysUserDao struct {
	*internal.SysUserDao
}

var (
	// SysUser is globally public accessible object for table sys_user operations.
	SysUser sysUserDao
)

func init() {
	SysUser = sysUserDao{
		internal.NewSysUserDao(),
	}
}

// Fill with you ideas below.
