// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"glow-admin/app/dao/internal"
	"glow-admin/app/model"
)

// sysMenuDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type sysMenuDao struct {
	*internal.SysMenuDao
}

var (
	// SysMenu is globally public accessible object for table sys_menu operations.
	SysMenu sysMenuDao
)

func init() {
	SysMenu = sysMenuDao{
		internal.NewSysMenuDao(),
	}
}

// Fill with you ideas below.

func GetPermissionsListByUserId(userID, pid uint) (res []*model.DTOMenu, err error) {
	db := SysMenu.As("m").
		Fields("DISTINCT m.*").
		InnerJoin("sys_role_menu as rm", "m.id=rm.menu_id").
		InnerJoin("sys_user_role as ur", "ur.role_id=rm.role_id").
		Where("ur.user_id=? AND m.type = 0 AND m.pid=? AND m.`status`=1", userID, pid).
		OrderAsc("m.sort")
	err = db.Scan(&res)
	return
}

func GetPermissionList(userID uint) (res []*model.DTOMenu, err error) {
	db := SysMenu.As("m").
		Fields("DISTINCT m.permission").
		InnerJoin("sys_role_menu as rm", "m.id=rm.menu_id").
		InnerJoin("sys_user_role as ur", "ur.role_id=rm.role_id").
		Where("ur.user_id = ? AND m.type = ? AND m.`status` = ?", userID, model.MenuTypeBtn, model.MenuStatusShow)
	err = db.Scan(&res)
	return
}
