// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"payget/app/dao/internal"
)

// sysAdDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type sysAdDao struct {
	*internal.SysAdDao
}

var (
	// SysAd is globally public accessible object for table sys_ad operations.
	SysAd sysAdDao
)

func init() {
	SysAd = sysAdDao{
		internal.NewSysAdDao(),
	}
}

// Fill with you ideas below.
