// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"payget/app/dao/internal"
)

// sysPositionDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type sysPositionDao struct {
	*internal.SysPositionDao
}

var (
	// SysPosition is globally public accessible object for table sys_position operations.
	SysPosition sysPositionDao
)

func init() {
	SysPosition = sysPositionDao{
		internal.NewSysPositionDao(),
	}
}

// Fill with you ideas below.
