// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"payget/app/dao/internal"
)

// sysItemDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type sysItemDao struct {
	*internal.SysItemDao
}

var (
	// SysItem is globally public accessible object for table sys_item operations.
	SysItem sysItemDao
)

func init() {
	SysItem = sysItemDao{
		internal.NewSysItemDao(),
	}
}

// Fill with you ideas below.
