// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"payget/app/dao/internal"
)

// sysLayoutDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type sysLayoutDao struct {
	*internal.SysLayoutDao
}

var (
	// SysLayout is globally public accessible object for table sys_layout operations.
	SysLayout sysLayoutDao
)

func init() {
	SysLayout = sysLayoutDao{
		internal.NewSysLayoutDao(),
	}
}

// Fill with you ideas below.
