// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"payget/app/dao/internal"
)

// sysLayoutDescDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type sysLayoutDescDao struct {
	*internal.SysLayoutDescDao
}

var (
	// SysLayoutDesc is globally public accessible object for table sys_layout_desc operations.
	SysLayoutDesc sysLayoutDescDao
)

func init() {
	SysLayoutDesc = sysLayoutDescDao{
		internal.NewSysLayoutDescDao(),
	}
}

// Fill with you ideas below.
