// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"glow-admin/app/dao/internal"
)

// sysLoginLogDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type sysLoginLogDao struct {
	*internal.SysLoginLogDao
}

var (
	// SysLoginLog is globally public accessible object for table sys_login_log operations.
	SysLoginLog sysLoginLogDao
)

func init() {
	SysLoginLog = sysLoginLogDao{
		internal.NewSysLoginLogDao(),
	}
}

// Fill with you ideas below.
