// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"payget/app/dao/internal"
)

// sysRoleMenuDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type sysRoleMenuDao struct {
	*internal.SysRoleMenuDao
}

var (
	// SysRoleMenu is globally public accessible object for table sys_role_menu operations.
	SysRoleMenu sysRoleMenuDao
)

func init() {
	SysRoleMenu = sysRoleMenuDao{
		internal.NewSysRoleMenuDao(),
	}
}

// Fill with you ideas below.
