// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"payget/app/dao/internal"
)

// sysDictDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type sysDictDao struct {
	*internal.SysDictDao
}

var (
	// SysDict is globally public accessible object for table sys_dict operations.
	SysDict sysDictDao
)

func init() {
	SysDict = sysDictDao{
		internal.NewSysDictDao(),
	}
}

// Fill with you ideas below.
