// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"payget/app/dao/internal"
)

// sysAdSortDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type sysAdSortDao struct {
	*internal.SysAdSortDao
}

var (
	// SysAdSort is globally public accessible object for table sys_ad_sort operations.
	SysAdSort sysAdSortDao
)

func init() {
	SysAdSort = sysAdSortDao{
		internal.NewSysAdSortDao(),
	}
}

// Fill with you ideas below.
