// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"payget/app/dao/internal"
)

// sysNoticeDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type sysNoticeDao struct {
	*internal.SysNoticeDao
}

var (
	// SysNotice is globally public accessible object for table sys_notice operations.
	SysNotice sysNoticeDao
)

func init() {
	SysNotice = sysNoticeDao{
		internal.NewSysNoticeDao(),
	}
}

// Fill with you ideas below.
