// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"payget/app/dao/internal"
)

// sysItemCateDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type sysItemCateDao struct {
	*internal.SysItemCateDao
}

var (
	// SysItemCate is globally public accessible object for table sys_item_cate operations.
	SysItemCate sysItemCateDao
)

func init() {
	SysItemCate = sysItemCateDao{
		internal.NewSysItemCateDao(),
	}
}

// Fill with you ideas below.
