// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// SysAdSortDao is the manager for logic model data accessing
// and custom defined data operations functions management.
type SysAdSortDao struct {
	gmvc.M                   // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	DB      gdb.DB           // DB is the raw underlying database management object.
	Table   string           // Table is the table name of the DAO.
	Columns sysAdSortColumns // Columns contains all the columns of Table that for convenient usage.
}

// SysAdSortColumns defines and stores column names for table sys_ad_sort.
type sysAdSortColumns struct {
	Id          string // 主键ID
	Name        string // 广告位名称
	Description string // 广告位描述
	ItemId      string // 站点ID
	CateId      string // 栏目ID
	LocId       string // 广告页面位置
	Platform    string // 站点类型：1PC网站 2WAP手机站 3微信小程序 4APP移动端
	Sort        string // 广告位排序
	CreateUser  string // 添加人
	CreateTime  string // 添加时间
	UpdateUser  string // 更新人
	UpdateTime  string // 更新时间
	Mark        string // 有效标识(1正常 0删除)
}

func NewSysAdSortDao() *SysAdSortDao {
	return &SysAdSortDao{
		M:     g.DB("default").Model("sys_ad_sort").Safe(),
		DB:    g.DB("default"),
		Table: "sys_ad_sort",
		Columns: sysAdSortColumns{
			Id:          "id",
			Name:        "name",
			Description: "description",
			ItemId:      "item_id",
			CateId:      "cate_id",
			LocId:       "loc_id",
			Platform:    "platform",
			Sort:        "sort",
			CreateUser:  "create_user",
			CreateTime:  "create_time",
			UpdateUser:  "update_user",
			UpdateTime:  "update_time",
			Mark:        "mark",
		},
	}
}
