// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// SysLayoutDescDao is the manager for logic model data accessing
// and custom defined data operations functions management.
type SysLayoutDescDao struct {
	gmvc.M                       // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	DB      gdb.DB               // DB is the raw underlying database management object.
	Table   string               // Table is the table name of the DAO.
	Columns sysLayoutDescColumns // Columns contains all the columns of Table that for convenient usage.
}

// SysLayoutDescColumns defines and stores column names for table sys_layout_desc.
type sysLayoutDescColumns struct {
	Id         string // 主键ID
	LocDesc    string // 页面位置描述
	LocId      string // 位置编号
	ItemId     string // 站点ID
	Sort       string // 排序
	CreateUser string // 添加人
	CreateTime string // 添加时间
	UpdateUser string // 更新人
	UpdateTime string // 更新时间
	Mark       string // 有效标识(1正常 0删除)
}

func NewSysLayoutDescDao() *SysLayoutDescDao {
	return &SysLayoutDescDao{
		M:     g.DB("default").Model("sys_layout_desc").Safe(),
		DB:    g.DB("default"),
		Table: "sys_layout_desc",
		Columns: sysLayoutDescColumns{
			Id:         "id",
			LocDesc:    "loc_desc",
			LocId:      "loc_id",
			ItemId:     "item_id",
			Sort:       "sort",
			CreateUser: "create_user",
			CreateTime: "create_time",
			UpdateUser: "update_user",
			UpdateTime: "update_time",
			Mark:       "mark",
		},
	}
}
