// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// SysUserDao is the manager for logic model data accessing
// and custom defined data operations functions management.
type SysUserDao struct {
	gmvc.M                 // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	DB      gdb.DB         // DB is the raw underlying database management object.
	Table   string         // Table is the table name of the DAO.
	Columns sysUserColumns // Columns contains all the columns of Table that for convenient usage.
}

// SysUserColumns defines and stores column names for table sys_user.
type sysUserColumns struct {
	Id           string // 主键ID
	Realname     string // 真实姓名
	Nickname     string // 昵称
	Gender       string // 性别:1男 2女 3保密
	Avatar       string // 头像
	Mobile       string // 手机号码
	Email        string // 邮箱地址
	Birthday     string // 出生日期
	DeptId       string // 部门ID
	LevelId      string // 职级ID
	PositionId   string // 岗位ID
	ProvinceCode string // 省份ID
	CityCode     string // 市区ID
	DistrictCode string // 区县ID
	Address      string // 详细地址
	CityName     string // 所属城市
	Username     string // 登录用户名
	Password     string // 登录密码
	Salt         string // 盐加密
	Intro        string // 个人简介
	Status       string // 状态：1正常 2禁用
	Note         string // 备注
	Sort         string // 显示顺序
	LoginNum     string // 登录次数
	LoginIp      string // 最近登录IP
	LoginTime    string // 最近登录时间
	CreateUser   string // 添加人
	CreateTime   string // 创建时间
	UpdateUser   string // 更新人
	UpdateTime   string // 更新时间
	Mark         string // 有效标识(1正常 0删除)
}

func NewSysUserDao() *SysUserDao {
	return &SysUserDao{
		M:     g.DB("default").Model("sys_user").Safe(),
		DB:    g.DB("default"),
		Table: "sys_user",
		Columns: sysUserColumns{
			Id:           "id",
			Realname:     "realname",
			Nickname:     "nickname",
			Gender:       "gender",
			Avatar:       "avatar",
			Mobile:       "mobile",
			Email:        "email",
			Birthday:     "birthday",
			DeptId:       "dept_id",
			LevelId:      "level_id",
			PositionId:   "position_id",
			ProvinceCode: "province_code",
			CityCode:     "city_code",
			DistrictCode: "district_code",
			Address:      "address",
			CityName:     "city_name",
			Username:     "username",
			Password:     "password",
			Salt:         "salt",
			Intro:        "intro",
			Status:       "status",
			Note:         "note",
			Sort:         "sort",
			LoginNum:     "login_num",
			LoginIp:      "login_ip",
			LoginTime:    "login_time",
			CreateUser:   "create_user",
			CreateTime:   "create_time",
			UpdateUser:   "update_user",
			UpdateTime:   "update_time",
			Mark:         "mark",
		},
	}
}
