// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// SysAdDao is the manager for logic model data accessing
// and custom defined data operations functions management.
type SysAdDao struct {
	gmvc.M               // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	DB      gdb.DB       // DB is the raw underlying database management object.
	Table   string       // Table is the table name of the DAO.
	Columns sysAdColumns // Columns contains all the columns of Table that for convenient usage.
}

// SysAdColumns defines and stores column names for table sys_ad.
type sysAdColumns struct {
	Id          string // 主键ID
	Title       string // 广告标题
	AdSortId    string // 广告位ID
	Cover       string // 广告图片
	Type        string // 广告格式：1图片 2文字 3视频 4推荐
	Description string // 广告描述
	Content     string // 广告内容
	Url         string // 广告链接
	Width       string // 广告宽度
	Height      string // 广告高度
	StartTime   string // 开始时间
	EndTime     string // 结束时间
	ViewNum     string // 广告点击次数
	Status      string // 状态：1在用 2停用
	Sort        string // 排序
	CreateUser  string // 添加人
	CreateTime  string // 添加时间
	UpdateUser  string // 更新人
	UpdateTime  string // 更新时间
	Mark        string // 有效标识(1正常 0删除)
}

func NewSysAdDao() *SysAdDao {
	return &SysAdDao{
		M:     g.DB("default").Model("sys_ad").Safe(),
		DB:    g.DB("default"),
		Table: "sys_ad",
		Columns: sysAdColumns{
			Id:          "id",
			Title:       "title",
			AdSortId:    "ad_sort_id",
			Cover:       "cover",
			Type:        "type",
			Description: "description",
			Content:     "content",
			Url:         "url",
			Width:       "width",
			Height:      "height",
			StartTime:   "start_time",
			EndTime:     "end_time",
			ViewNum:     "view_num",
			Status:      "status",
			Sort:        "sort",
			CreateUser:  "create_user",
			CreateTime:  "create_time",
			UpdateUser:  "update_user",
			UpdateTime:  "update_time",
			Mark:        "mark",
		},
	}
}
