// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// SysConfigDao is the manager for logic model data accessing and custom defined data operations functions management.
type SysConfigDao struct {
	gmvc.M                  // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	C      sysConfigColumns // C is the short type for Columns, which contains all the column names of Table for convenient usage.
	DB     gdb.DB           // DB is the raw underlying database management object.
	Table  string           // Table is the underlying table name of the DAO.
}

// SysConfigColumns defines and stores column names for table sys_config.
type sysConfigColumns struct {
	Id          string // 主键ID
	Name        string // 分组名称
	Sort        string // 排序
	CreatedBy   string // 添加人
	CreatedAt   string // 创建时间
	UpdatedBy   string // 更新人
	UpdatedAt   string // 最后更新时间
	ConfigName  string // ConfigName
	ConfigKey   string // ConfigKey
	IsFrontend  string // 是否前台
	CreateBy    string // 创建者
	UpdateBy    string // 更新者
	ConfigValue string // ConfigValue
	ConfigType  string // ConfigType
	Remark      string // Remark
	DeletedAt   string // 删除时间
}

// NewSysConfigDao creates and returns a new DAO object for table data access.
func NewSysConfigDao() *SysConfigDao {
	columns := sysConfigColumns{
		Id:          "id",
		Name:        "name",
		Sort:        "sort",
		CreatedBy:   "created_by",
		CreatedAt:   "created_at",
		UpdatedBy:   "updated_by",
		UpdatedAt:   "updated_at",
		ConfigName:  "config_name",
		ConfigKey:   "config_key",
		IsFrontend:  "is_frontend",
		CreateBy:    "create_by",
		UpdateBy:    "update_by",
		ConfigValue: "config_value",
		ConfigType:  "config_type",
		Remark:      "remark",
		DeletedAt:   "deleted_at",
	}
	return &SysConfigDao{
		C:     columns,
		M:     g.DB("default").Model("sys_config").Safe(),
		DB:    g.DB("default"),
		Table: "sys_config",
	}
}
