// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// SysUserRoleDao is the manager for logic model data accessing
// and custom defined data operations functions management.
type SysUserRoleDao struct {
	gmvc.M                     // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	DB      gdb.DB             // DB is the raw underlying database management object.
	Table   string             // Table is the table name of the DAO.
	Columns sysUserRoleColumns // Columns contains all the columns of Table that for convenient usage.
}

// SysUserRoleColumns defines and stores column names for table sys_user_role.
type sysUserRoleColumns struct {
	UserId string // 人员ID
	RoleId string // 角色ID
}

func NewSysUserRoleDao() *SysUserRoleDao {
	return &SysUserRoleDao{
		M:     g.DB("default").Model("sys_user_role").Safe(),
		DB:    g.DB("default"),
		Table: "sys_user_role",
		Columns: sysUserRoleColumns{
			UserId: "user_id",
			RoleId: "role_id",
		},
	}
}
