// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// SysUserDao is the manager for logic model data accessing
// and custom defined data operations functions management.
type SysUserDao struct {
	gmvc.M                 // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	DB      gdb.DB         // DB is the raw underlying database management object.
	Table   string         // Table is the table name of the DAO.
	Columns sysUserColumns // Columns contains all the columns of Table that for convenient usage.
}

// SysUserColumns defines and stores column names for table sys_user.
type sysUserColumns struct {
	Id        string // 主键ID
	Nickname  string // 昵称
	Username  string // 登录用户名
	Password  string // 登录密码
	Salt      string // 盐加密
	Avatar    string // 头像
	Mobile    string // 手机号码
	Email     string // 邮箱地址
	Intro     string // 个人简介
	Status    string // 状态：1正常 2禁用
	Note      string // 备注
	LoginNum  string // 登录次数
	LoginIp   string // 最近登录IP
	LoginTime string // 最近登录时间
	CreatedBy string // 添加人
	CreatedAt string // 添加时间
	UpdatedBy string // 更新人
	UpdatedAt string // 更新时间
}

func NewSysUserDao() *SysUserDao {
	return &SysUserDao{
		M:     g.DB("default").Model("sys_user").Safe(),
		DB:    g.DB("default"),
		Table: "sys_user",
		Columns: sysUserColumns{
			Id:        "id",
			Nickname:  "nickname",
			Username:  "username",
			Password:  "password",
			Salt:      "salt",
			Avatar:    "avatar",
			Mobile:    "mobile",
			Email:     "email",
			Intro:     "intro",
			Status:    "status",
			Note:      "note",
			LoginNum:  "login_num",
			LoginIp:   "login_ip",
			LoginTime: "login_time",
			CreatedBy: "created_by",
			CreatedAt: "created_at",
			UpdatedBy: "updated_by",
			UpdatedAt: "updated_at",
		},
	}
}
