// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// SysLayoutDao is the manager for logic model data accessing
// and custom defined data operations functions management.
type SysLayoutDao struct {
	gmvc.M                   // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	DB      gdb.DB           // DB is the raw underlying database management object.
	Table   string           // Table is the table name of the DAO.
	Columns sysLayoutColumns // Columns contains all the columns of Table that for convenient usage.
}

// SysLayoutColumns defines and stores column names for table sys_layout.
type sysLayoutColumns struct {
	Id         string // 主键ID
	LocDesc    string // 页面位置描述
	LocId      string // 页面的位置
	ItemId     string // 页面编号
	Type       string // 类型：1系统文章 2通知公告
	TypeId     string // 对应的类型编号
	Image      string // 图片路径
	Sort       string // 显示顺序
	CreateUser string // 添加人
	CreateTime string // 添加时间
	UpdateUser string // 更新人
	UpdateTime string // 更新时间
	Mark       string // 有效标识(1正常 0删除)
}

func NewSysLayoutDao() *SysLayoutDao {
	return &SysLayoutDao{
		M:     g.DB("default").Model("sys_layout").Safe(),
		DB:    g.DB("default"),
		Table: "sys_layout",
		Columns: sysLayoutColumns{
			Id:         "id",
			LocDesc:    "loc_desc",
			LocId:      "loc_id",
			ItemId:     "item_id",
			Type:       "type",
			TypeId:     "type_id",
			Image:      "image",
			Sort:       "sort",
			CreateUser: "create_user",
			CreateTime: "create_time",
			UpdateUser: "update_user",
			UpdateTime: "update_time",
			Mark:       "mark",
		},
	}
}
