// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// SysRoleMenuDao is the manager for logic model data accessing and custom defined data operations functions management.
type SysRoleMenuDao struct {
	gmvc.M                    // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	C      sysRoleMenuColumns // C is the short type for Columns, which contains all the column names of Table for convenient usage.
	DB     gdb.DB             // DB is the raw underlying database management object.
	Table  string             // Table is the underlying table name of the DAO.
}

// SysRoleMenuColumns defines and stores column names for table sys_role_menu.
type sysRoleMenuColumns struct {
	RoleId string // 角色ID
	MenuId string // 菜单ID
}

// NewSysRoleMenuDao creates and returns a new DAO object for table data access.
func NewSysRoleMenuDao() *SysRoleMenuDao {
	columns := sysRoleMenuColumns{
		RoleId: "role_id",
		MenuId: "menu_id",
	}
	return &SysRoleMenuDao{
		C:     columns,
		M:     g.DB("default").Model("sys_role_menu").Safe(),
		DB:    g.DB("default"),
		Table: "sys_role_menu",
	}
}
