// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// SysUserRoleDao is the manager for logic model data accessing and custom defined data operations functions management.
type SysUserRoleDao struct {
	gmvc.M                    // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	C      sysUserRoleColumns // C is the short type for Columns, which contains all the column names of Table for convenient usage.
	DB     gdb.DB             // DB is the raw underlying database management object.
	Table  string             // Table is the underlying table name of the DAO.
}

// SysUserRoleColumns defines and stores column names for table sys_user_role.
type sysUserRoleColumns struct {
	UserId string // 人员ID
	RoleId string // 角色ID
}

// NewSysUserRoleDao creates and returns a new DAO object for table data access.
func NewSysUserRoleDao() *SysUserRoleDao {
	columns := sysUserRoleColumns{
		UserId: "user_id",
		RoleId: "role_id",
	}
	return &SysUserRoleDao{
		C:     columns,
		M:     g.DB("default").Model("sys_user_role").Safe(),
		DB:    g.DB("default"),
		Table: "sys_user_role",
	}
}
