// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// SysItemCateDao is the manager for logic model data accessing
// and custom defined data operations functions management.
type SysItemCateDao struct {
	gmvc.M                     // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	DB      gdb.DB             // DB is the raw underlying database management object.
	Table   string             // Table is the table name of the DAO.
	Columns sysItemCateColumns // Columns contains all the columns of Table that for convenient usage.
}

// SysItemCateColumns defines and stores column names for table sys_item_cate.
type sysItemCateColumns struct {
	Id         string // ID
	Name       string // 栏目名称
	Pid        string // 父级ID
	ItemId     string // 站点ID
	Pinyin     string // 拼音(全)
	Code       string // 拼音(简)
	Cover      string // 封面
	Status     string // 状态：1启用 2停用
	Note       string // 备注
	Sort       string // 排序
	CreateUser string // 添加人
	CreateTime string // 添加时间
	UpdateUser string // 更新人
	UpdateTime string // 更新时间
	Mark       string // 有效标识(1正常 0删除)
}

func NewSysItemCateDao() *SysItemCateDao {
	return &SysItemCateDao{
		M:     g.DB("default").Model("sys_item_cate").Safe(),
		DB:    g.DB("default"),
		Table: "sys_item_cate",
		Columns: sysItemCateColumns{
			Id:         "id",
			Name:       "name",
			Pid:        "pid",
			ItemId:     "item_id",
			Pinyin:     "pinyin",
			Code:       "code",
			Cover:      "cover",
			Status:     "status",
			Note:       "note",
			Sort:       "sort",
			CreateUser: "create_user",
			CreateTime: "create_time",
			UpdateUser: "update_user",
			UpdateTime: "update_time",
			Mark:       "mark",
		},
	}
}
