// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// SysCityDao is the manager for logic model data accessing
// and custom defined data operations functions management.
type SysCityDao struct {
	gmvc.M                 // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	DB      gdb.DB         // DB is the raw underlying database management object.
	Table   string         // Table is the table name of the DAO.
	Columns sysCityColumns // Columns contains all the columns of Table that for convenient usage.
}

// SysCityColumns defines and stores column names for table sys_city.
type sysCityColumns struct {
	Id         string // 编号
	Pid        string // 父级编号
	Level      string // 城市级别：1省 2市 3区
	Name       string // 城市名称
	Citycode   string // 城市编号（区号）
	PAdcode    string // 父级地理编号
	Adcode     string // 地理编号
	Lng        string // 城市坐标中心点经度（* 1e6）：如果是中国，此值是 1e7
	Lat        string // 城市坐标中心点纬度（* 1e6）
	Sort       string // 排序号
	CreateUser string // 添加人
	CreateTime string // 添加时间
	UpdateUser string // 更新人
	UpdateTime string // 更新时间
	Mark       string // 有效标记
}

func NewSysCityDao() *SysCityDao {
	return &SysCityDao{
		M:     g.DB("default").Model("sys_city").Safe(),
		DB:    g.DB("default"),
		Table: "sys_city",
		Columns: sysCityColumns{
			Id:         "id",
			Pid:        "pid",
			Level:      "level",
			Name:       "name",
			Citycode:   "citycode",
			PAdcode:    "p_adcode",
			Adcode:     "adcode",
			Lng:        "lng",
			Lat:        "lat",
			Sort:       "sort",
			CreateUser: "create_user",
			CreateTime: "create_time",
			UpdateUser: "update_user",
			UpdateTime: "update_time",
			Mark:       "mark",
		},
	}
}
