// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// SysLinkDao is the manager for logic model data accessing
// and custom defined data operations functions management.
type SysLinkDao struct {
	gmvc.M                 // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	DB      gdb.DB         // DB is the raw underlying database management object.
	Table   string         // Table is the table name of the DAO.
	Columns sysLinkColumns // Columns contains all the columns of Table that for convenient usage.
}

// SysLinkColumns defines and stores column names for table sys_link.
type sysLinkColumns struct {
	Id         string // 唯一性标识
	Name       string // 友链名称
	Type       string // 类型：1友情链接 2合作伙伴
	Url        string // 友链地址
	ItemId     string // 站点ID
	CateId     string // 栏目ID
	Platform   string // 平台：1PC站 2WAP站 3微信小程序 4APP应用
	Form       string // 友链形式：1文字链接 2图片链接
	Image      string // 友链图片
	Status     string // 状态：1在用 2停用
	Sort       string // 显示顺序
	CreateUser string // 添加人
	CreateTime string // 添加时间
	UpdateUser string // 更新人
	UpdateTime string // 更新时间
	Mark       string // 有效标识(1正常 0删除)
}

func NewSysLinkDao() *SysLinkDao {
	return &SysLinkDao{
		M:     g.DB("default").Model("sys_link").Safe(),
		DB:    g.DB("default"),
		Table: "sys_link",
		Columns: sysLinkColumns{
			Id:         "id",
			Name:       "name",
			Type:       "type",
			Url:        "url",
			ItemId:     "item_id",
			CateId:     "cate_id",
			Platform:   "platform",
			Form:       "form",
			Image:      "image",
			Status:     "status",
			Sort:       "sort",
			CreateUser: "create_user",
			CreateTime: "create_time",
			UpdateUser: "update_user",
			UpdateTime: "update_time",
			Mark:       "mark",
		},
	}
}
