// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// SysLevelDao is the manager for logic model data accessing
// and custom defined data operations functions management.
type SysLevelDao struct {
	gmvc.M                  // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	DB      gdb.DB          // DB is the raw underlying database management object.
	Table   string          // Table is the table name of the DAO.
	Columns sysLevelColumns // Columns contains all the columns of Table that for convenient usage.
}

// SysLevelColumns defines and stores column names for table sys_level.
type sysLevelColumns struct {
	Id         string // 主键ID
	Name       string // 职级名称
	Status     string // 状态：1正常 2停用
	Sort       string // 显示顺序
	CreateUser string // 添加人
	CreateTime string // 创建时间
	UpdateUser string // 更新人
	UpdateTime string // 更新时间
	Mark       string // 有效标识
}

func NewSysLevelDao() *SysLevelDao {
	return &SysLevelDao{
		M:     g.DB("default").Model("sys_level").Safe(),
		DB:    g.DB("default"),
		Table: "sys_level",
		Columns: sysLevelColumns{
			Id:         "id",
			Name:       "name",
			Status:     "status",
			Sort:       "sort",
			CreateUser: "create_user",
			CreateTime: "create_time",
			UpdateUser: "update_user",
			UpdateTime: "update_time",
			Mark:       "mark",
		},
	}
}
