// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// SysDictDao is the manager for logic model data accessing
// and custom defined data operations functions management.
type SysDictDao struct {
	gmvc.M                 // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	DB      gdb.DB         // DB is the raw underlying database management object.
	Table   string         // Table is the table name of the DAO.
	Columns sysDictColumns // Columns contains all the columns of Table that for convenient usage.
}

// SysDictColumns defines and stores column names for table sys_dict.
type sysDictColumns struct {
	Id         string // 主键ID
	Name       string // 字典名称
	Code       string // 字典值
	Sort       string // 显示顺序
	Note       string // 字典备注
	CreateUser string // 添加人
	CreateTime string // 添加时间
	UpdateUser string // 更新人
	UpdateTime string // 更新时间
	Mark       string // 有效标识
}

func NewSysDictDao() *SysDictDao {
	return &SysDictDao{
		M:     g.DB("default").Model("sys_dict").Safe(),
		DB:    g.DB("default"),
		Table: "sys_dict",
		Columns: sysDictColumns{
			Id:         "id",
			Name:       "name",
			Code:       "code",
			Sort:       "sort",
			Note:       "note",
			CreateUser: "create_user",
			CreateTime: "create_time",
			UpdateUser: "update_user",
			UpdateTime: "update_time",
			Mark:       "mark",
		},
	}
}
