// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// SysItemDao is the manager for logic model data accessing
// and custom defined data operations functions management.
type SysItemDao struct {
	gmvc.M                 // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	DB      gdb.DB         // DB is the raw underlying database management object.
	Table   string         // Table is the table name of the DAO.
	Columns sysItemColumns // Columns contains all the columns of Table that for convenient usage.
}

// SysItemColumns defines and stores column names for table sys_item.
type sysItemColumns struct {
	Id         string // 唯一性标识
	Name       string // 站点名称
	Type       string // 站点类型:1普通站点 2其他
	Url        string // 站点地址
	Image      string // 站点图片
	IsDomain   string // 是否二级域名:1是 2否
	Status     string // 状态：1在用 2停用
	Note       string // 站点备注
	Sort       string // 显示顺序
	CreateUser string // 添加人
	CreateTime string // 添加时间
	UpdateUser string // 更新人
	UpdateTime string // 更新时间
	Mark       string // 有效标识(1正常 0删除)
}

func NewSysItemDao() *SysItemDao {
	return &SysItemDao{
		M:     g.DB("default").Model("sys_item").Safe(),
		DB:    g.DB("default"),
		Table: "sys_item",
		Columns: sysItemColumns{
			Id:         "id",
			Name:       "name",
			Type:       "type",
			Url:        "url",
			Image:      "image",
			IsDomain:   "is_domain",
			Status:     "status",
			Note:       "note",
			Sort:       "sort",
			CreateUser: "create_user",
			CreateTime: "create_time",
			UpdateUser: "update_user",
			UpdateTime: "update_time",
			Mark:       "mark",
		},
	}
}
