// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// SysRoleMenuDao is the manager for logic model data accessing
// and custom defined data operations functions management.
type SysRoleMenuDao struct {
	gmvc.M                     // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	DB      gdb.DB             // DB is the raw underlying database management object.
	Table   string             // Table is the table name of the DAO.
	Columns sysRoleMenuColumns // Columns contains all the columns of Table that for convenient usage.
}

// SysRoleMenuColumns defines and stores column names for table sys_role_menu.
type sysRoleMenuColumns struct {
	RoleId string // 角色ID
	MenuId string // 菜单ID
}

func NewSysRoleMenuDao() *SysRoleMenuDao {
	return &SysRoleMenuDao{
		M:     g.DB("default").Model("sys_role_menu").Safe(),
		DB:    g.DB("default"),
		Table: "sys_role_menu",
		Columns: sysRoleMenuColumns{
			RoleId: "role_id",
			MenuId: "menu_id",
		},
	}
}
