// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// SysNoticeDao is the manager for logic model data accessing
// and custom defined data operations functions management.
type SysNoticeDao struct {
	gmvc.M                   // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	DB      gdb.DB           // DB is the raw underlying database management object.
	Table   string           // Table is the table name of the DAO.
	Columns sysNoticeColumns // Columns contains all the columns of Table that for convenient usage.
}

// SysNoticeColumns defines and stores column names for table sys_notice.
type sysNoticeColumns struct {
	Id         string // 通知ID
	Title      string // 通知标题
	Content    string // 通知内容
	Source     string // 来源：1内部通知 2外部新闻
	IsTop      string // 是否置顶：1是 2否
	Browse     string // 阅读量
	Status     string // 状态：1已发布 2待发布
	CreateUser string // 添加人
	CreateTime string // 添加时间
	UpdateUser string // 更新人
	UpdateTime string // 更新时间
	Mark       string // 有效标识
}

func NewSysNoticeDao() *SysNoticeDao {
	return &SysNoticeDao{
		M:     g.DB("default").Model("sys_notice").Safe(),
		DB:    g.DB("default"),
		Table: "sys_notice",
		Columns: sysNoticeColumns{
			Id:         "id",
			Title:      "title",
			Content:    "content",
			Source:     "source",
			IsTop:      "is_top",
			Browse:     "browse",
			Status:     "status",
			CreateUser: "create_user",
			CreateTime: "create_time",
			UpdateUser: "update_user",
			UpdateTime: "update_time",
			Mark:       "mark",
		},
	}
}
