// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// SysExampleDao is the manager for logic model data accessing
// and custom defined data operations functions management.
type SysExampleDao struct {
	gmvc.M                    // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	DB      gdb.DB            // DB is the raw underlying database management object.
	Table   string            // Table is the table name of the DAO.
	Columns sysExampleColumns // Columns contains all the columns of Table that for convenient usage.
}

// SysExampleColumns defines and stores column names for table sys_example.
type sysExampleColumns struct {
	Id         string // 唯一性标识
	Name       string // 案例名称
	Avatar     string // 头像
	Status     string // 状态：1正常 2停用
	Type       string // 类型：1京东 2淘宝 3拼多多 4唯品会
	Sort       string // 显示顺序
	Birthday   string // 出生时间
	CreateUser string // 添加人
	CreateTime string // 添加时间
	UpdateUser string // 更新人
	UpdateTime string // 更新时间
	Mark       string // 有效标记
}

func NewSysExampleDao() *SysExampleDao {
	return &SysExampleDao{
		M:     g.DB("default").Model("sys_example").Safe(),
		DB:    g.DB("default"),
		Table: "sys_example",
		Columns: sysExampleColumns{
			Id:         "id",
			Name:       "name",
			Avatar:     "avatar",
			Status:     "status",
			Type:       "type",
			Sort:       "sort",
			Birthday:   "birthday",
			CreateUser: "create_user",
			CreateTime: "create_time",
			UpdateUser: "update_user",
			UpdateTime: "update_time",
			Mark:       "mark",
		},
	}
}
