// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// UmsMemberLevelDao is the manager for logic model data accessing
// and custom defined data operations functions management.
type UmsMemberLevelDao struct {
	gmvc.M                        // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	DB      gdb.DB                // DB is the raw underlying database management object.
	Table   string                // Table is the table name of the DAO.
	Columns umsMemberLevelColumns // Columns contains all the columns of Table that for convenient usage.
}

// UmsMemberLevelColumns defines and stores column names for table ums_member_level.
type umsMemberLevelColumns struct {
	Id         string // 主键ID
	Name       string // 级别名称
	Sort       string // 显示顺序
	CreateUser string // 添加人
	CreateTime string // 创建时间
	UpdateUser string // 更新人
	UpdateTime string // 更新时间
	Mark       string // 有效标识
}

func NewUmsMemberLevelDao() *UmsMemberLevelDao {
	return &UmsMemberLevelDao{
		M:     g.DB("default").Model("ums_member_level").Safe(),
		DB:    g.DB("default"),
		Table: "ums_member_level",
		Columns: umsMemberLevelColumns{
			Id:         "id",
			Name:       "name",
			Sort:       "sort",
			CreateUser: "create_user",
			CreateTime: "create_time",
			UpdateUser: "update_user",
			UpdateTime: "update_time",
			Mark:       "mark",
		},
	}
}
