// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// UmsMemberDao is the manager for logic model data accessing
// and custom defined data operations functions management.
type UmsMemberDao struct {
	gmvc.M                   // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	DB      gdb.DB           // DB is the raw underlying database management object.
	Table   string           // Table is the table name of the DAO.
	Columns umsMemberColumns // Columns contains all the columns of Table that for convenient usage.
}

// UmsMemberColumns defines and stores column names for table ums_member.
type umsMemberColumns struct {
	Id           string //
	Openid       string // 用户唯一标识
	Mobile       string // 手机号
	Password     string // 密码
	MemberLevel  string // 会员等级
	Realname     string // 真实姓名
	Nickname     string // 用户昵称
	Gender       string // 性别（1男 2女 3未知）
	Avatar       string // 用户头像
	Birthday     string // 出生日期
	ProvinceCode string // 户籍省份编号
	CityCode     string // 户籍城市编号
	DistrictCode string // 户籍区/县编号
	Address      string // 详细地址
	Intro        string // 个人简介
	Signature    string // 个性签名
	Device       string // 设备类型：1苹果 2安卓 3WAP站 4PC站 5后台添加
	DeviceCode   string // 推送的别名
	LoginStatus  string // 用户状态(1登录 2登出)
	PushAlias    string // 推送的别名
	Source       string // 来源：1、APP注册；2、后台添加；
	Status       string // 是否启用 1、启用  2、停用
	AppVersion   string // 客户端版本号
	Code         string // 我的推广码
	LoginIp      string // 最近登录IP
	LoginTime    string // 登录时间
	LoginRegion  string // 上次登录地点
	LoginCount   string // 登录总次数
	CreateUser   string // 添加人
	CreateTime   string // 创建时间
	UpdateUser   string // 修改人
	UpdateTime   string // 更新时间
	Mark         string // 有效标识：1正常 0删除
}

func NewUmsMemberDao() *UmsMemberDao {
	return &UmsMemberDao{
		M:     g.DB("default").Model("ums_member").Safe(),
		DB:    g.DB("default"),
		Table: "ums_member",
		Columns: umsMemberColumns{
			Id:           "id",
			Openid:       "openid",
			Mobile:       "mobile",
			Password:     "password",
			MemberLevel:  "member_level",
			Realname:     "realname",
			Nickname:     "nickname",
			Gender:       "gender",
			Avatar:       "avatar",
			Birthday:     "birthday",
			ProvinceCode: "province_code",
			CityCode:     "city_code",
			DistrictCode: "district_code",
			Address:      "address",
			Intro:        "intro",
			Signature:    "signature",
			Device:       "device",
			DeviceCode:   "device_code",
			LoginStatus:  "login_status",
			PushAlias:    "push_alias",
			Source:       "source",
			Status:       "status",
			AppVersion:   "app_version",
			Code:         "code",
			LoginIp:      "login_ip",
			LoginTime:    "login_time",
			LoginRegion:  "login_region",
			LoginCount:   "login_count",
			CreateUser:   "create_user",
			CreateTime:   "create_time",
			UpdateUser:   "update_user",
			UpdateTime:   "update_time",
			Mark:         "mark",
		},
	}
}
